spring.application.name=ZJournalServer
server.port=8080

zjournal.encryption-key=JagaBaliaShreekhetra
zjournal.db-file=db.json
zjournal.encryption-enabled=true

springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.display-request-duration=true
